apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-from-manifests
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: example-from-manifests
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/ondrejsika/cloud-native-bratislava-argocd-test.git
    targetRevision: HEAD
    path: apps/sikademo/example_from_manifests/manifests
