apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-cd
      targetRevision: 7.8.12
      helm:
        valueFiles:
          - $values/apps/us/_system/argocd/argocd.values.yaml
    - repoURL: https://github.com/ondrejsika/cloud-native-bratislava-argocd-test.git
      targetRevision: HEAD
      ref: values
