apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  sources:
    - repoURL: https://github.com/ondrejsika/cloud-native-bratislava-argocd-test.git
      path: apps/_global
      targetRevision: HEAD
      directory:
        recurse: true
        exclude: '{**/manifests/**,**/Chart.yaml,**/values.yaml,**/templates/**,**/*.values.yaml}'
    - repoURL: https://github.com/ondrejsika/cloud-native-bratislava-argocd-test.git
      path: apps/eu
      targetRevision: HEAD
      directory:
        recurse: true
        exclude: '{**/manifests/**,**/Chart.yaml,**/values.yaml,**/templates/**,**/*.values.yaml}'
    - repoURL: https://github.com/ondrejsika/cloud-native-bratislava-argocd-test.git
      path: clusters/eu
      targetRevision: HEAD
      directory:
        recurse: true
        exclude: '{**/manifests/**,**/Chart.yaml,**/values.yaml,**/templates/**,**/*.values.yaml}'
